<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllClient($colonne, $order, $nbItem, $page){
        $query = $this->createQueryBuilder('c');
        if($colonne){
            $query->orderBy($colonne, $order);
        }
        if($nbItem){
            $query->setMaxResults($nbItem);
        }

        return $query->getQuery()->getResult();
    }
}
